<script>
  let width = null;
  import { onMount } from "svelte";
  export let onAiMounted = () => {};
  onMount(() => {
    onAiMounted();
  });
</script>


<!-- Generated by ai2html v0.116.0 - 2026-04-20 11:40 -->
<!-- ai file: netherlands-carillon-locator.ai -->


<div id="g-netherlands-carillon-locator-box" class="ai2html" bind:clientWidth={width}>

	<!-- Artboard: mobile-small -->
{#if width && ( width >= 0 && width <329)}	<div id="g-netherlands-carillon-locator-mobile-small" class="g-artboard" style="" data-aspect-ratio="0.898" data-min-width="0" data-max-width="328">
<div style="padding: 0 0 111.4053% 0;"></div>
		<img id="g-netherlands-carillon-locator-mobile-small-img" class="g-netherlands-carillon-locator-mobile-small-img g-aiImg" alt="" src="./images/netherlands-carillon-locator-mobile-small.jpg"/>
		<div id="g-ai0-1" class="g-text-shadow g-aiAbs g-aiPointText" style="top:5.1164%;margin-top:-12.7px;left:12.6343%;width:112px;">
			<p class="g-pstyle0">Arlington National</p>
			<p class="g-pstyle0">Cemetary</p>
		</div>
		<div id="g-ai0-2" class="g-text-shadow g-aiAbs g-aiPointText" style="top:5.1164%;margin-top:-12.7px;left:62.0867%;width:112px;">
			<p class="g-pstyle0">U.S. Marine Corps</p>
			<p class="g-pstyle0">War Memorial</p>
		</div>
		<div id="g-ai0-3" class="g-text-shadow g-aiAbs g-aiPointText" style="top:30.2935%;margin-top:-12.7px;left:68.8155%;width:82px;">
			<p class="g-pstyle0">Netherlands</p>
			<p class="g-pstyle0">Carillon</p>
		</div>
		<div id="g-ai0-4" class="g-text-shadow g-aiAbs g-aiPointText" style="top:56.2573%;margin-top:-10.6px;left:80.5765%;margin-left:-36px;width:72px;">
			<p class="g-pstyle1">Additional</p>
			<p class="g-pstyle1">garden beds</p>
		</div>
		<div id="g-ai0-5" class="g-text-shadow g-aiAbs g-aiPointText" style="top:55.7444%;margin-top:-6.7px;left:11.6498%;width:29px;">
			<p class="g-pstyle0">C</p>
		</div>
		<div id="g-ai0-6" class="g-text-shadow g-aiAbs g-aiPointText" style="top:66.6911%;margin-top:-6.7px;left:2.7909%;width:29px;">
			<p class="g-pstyle0">D</p>
		</div>
		<div id="g-ai0-7" class="g-text-shadow g-aiAbs g-aiPointText" style="top:67.2385%;margin-top:-6.7px;left:90.7569%;width:29px;">
			<p class="g-pstyle0">A</p>
		</div>
		<div id="g-ai0-8" class="g-text-shadow g-aiAbs g-aiPointText" style="top:68.6067%;margin-top:-6.7px;left:70.4538%;width:29px;">
			<p class="g-pstyle0">B</p>
		</div>
		<div id="g-ai0-9" class="g-text-shadow g-aiAbs g-aiPointText" style="top:77.6377%;margin-top:-6.7px;left:38.435%;width:73px;">
			<p class="g-pstyle0">Beds 1-49</p>
		</div>
		<div id="g-ai0-10" class="g-text-shadow g-aiAbs g-aiPointText" style="top:80.6481%;margin-top:-6.7px;left:7.0594%;width:28px;">
			<p class="g-pstyle0">E</p>
		</div>
		<div id="g-ai0-11" class="g-other g-aiAbs g-aiPointText" style="top:86.9077%;margin-top:-6.6px;left:91.353%;margin-left:-29.5px;width:59px;">
			<p class="g-pstyle2">Arlington</p>
		</div>
		<div id="g-ai0-12" class="g-other g-aiAbs g-aiPointText" style="top:94.6197%;margin-top:-5.7px;left:71.0786%;width:62px;">
			<p class="g-pstyle3">VIRGINIA</p>
		</div>
	</div>
{/if}
	<!-- Artboard: mobile-large -->
{#if width && ( width >= 329 && width <599)}	<div id="g-netherlands-carillon-locator-mobile-large" class="g-artboard" style="" data-aspect-ratio="0.89" data-min-width="329" data-max-width="598">
<div style="padding: 0 0 112.2995% 0;"></div>
		<img id="g-netherlands-carillon-locator-mobile-large-img" class="g-netherlands-carillon-locator-mobile-large-img g-aiImg" alt="" src="./images/netherlands-carillon-locator-mobile-large.jpg"/>
		<div id="g-ai1-1" class="g-text-shadow g-aiAbs g-aiPointText" style="top:5.4339%;margin-top:-14.8px;left:12.6403%;width:128px;">
			<p class="g-pstyle0">Arlington National</p>
			<p class="g-pstyle0">Cemetary</p>
		</div>
		<div id="g-ai1-2" class="g-text-shadow g-aiAbs g-aiPointText" style="top:5.4339%;margin-top:-14.8px;left:62.1168%;width:128px;">
			<p class="g-pstyle0">U.S. Marine Corps</p>
			<p class="g-pstyle0">War Memorial</p>
		</div>
		<div id="g-ai1-3" class="g-text-shadow g-aiAbs g-aiPointText" style="top:30.1957%;margin-top:-14.8px;left:68.849%;width:93px;">
			<p class="g-pstyle0">Netherlands</p>
			<p class="g-pstyle0">Carillon</p>
		</div>
		<div id="g-ai1-4" class="g-text-shadow g-aiAbs g-aiPointText" style="top:56.118%;margin-top:-12.7px;left:80.6056%;margin-left:-41.5px;width:83px;">
			<p class="g-pstyle1">Additional</p>
			<p class="g-pstyle1">garden beds</p>
		</div>
		<div id="g-ai1-5" class="g-text-shadow g-aiAbs g-aiPointText" style="top:55.4338%;margin-top:-8.8px;left:11.6554%;width:31px;">
			<p class="g-pstyle2">C</p>
		</div>
		<div id="g-ai1-6" class="g-text-shadow g-aiAbs g-aiPointText" style="top:66.148%;margin-top:-8.8px;left:2.7923%;width:30px;">
			<p class="g-pstyle2">D</p>
		</div>
		<div id="g-ai1-7" class="g-text-shadow g-aiAbs g-aiPointText" style="top:66.8623%;margin-top:-8.8px;left:90.801%;width:31px;">
			<p class="g-pstyle2">A</p>
		</div>
		<div id="g-ai1-8" class="g-text-shadow g-aiAbs g-aiPointText" style="top:68.0528%;margin-top:-8.8px;left:70.488%;width:30px;">
			<p class="g-pstyle2">B</p>
		</div>
		<div id="g-ai1-9" class="g-text-shadow g-aiAbs g-aiPointText" style="top:77.3385%;margin-top:-8.8px;left:38.4537%;width:82px;">
			<p class="g-pstyle2">Beds 1-49</p>
		</div>
		<div id="g-ai1-10" class="g-text-shadow g-aiAbs g-aiPointText" style="top:80.1958%;margin-top:-8.8px;left:7.0628%;width:29px;">
			<p class="g-pstyle2">E</p>
		</div>
		<div id="g-ai1-11" class="g-other g-aiAbs g-aiPointText" style="top:86.1179%;margin-top:-7.7px;left:91.4978%;margin-left:-34px;width:68px;">
			<p class="g-pstyle3">Arlington</p>
		</div>
		<div id="g-ai1-12" class="g-other g-aiAbs g-aiPointText" style="top:93.909%;margin-top:-6.4px;left:71.1131%;width:68px;">
			<p class="g-pstyle4">VIRGINIA</p>
		</div>
	</div>
{/if}
	<!-- Artboard: tablet -->
{#if width && ( width >= 599 && width <785)}	<div id="g-netherlands-carillon-locator-tablet" class="g-artboard" style="" data-aspect-ratio="1.56" data-min-width="599" data-max-width="784">
<div style="padding: 0 0 64.1036% 0;"></div>
		<img id="g-netherlands-carillon-locator-tablet-img" class="g-netherlands-carillon-locator-tablet-img g-aiImg" alt="" src="./images/netherlands-carillon-locator-tablet.jpg"/>
		<div id="g-ai2-1" class="g-text-shadow g-aiAbs g-aiPointText" style="top:20.7698%;margin-top:-15.9px;left:5.2731%;width:136px;">
			<p class="g-pstyle0">Arlington National</p>
			<p class="g-pstyle0">Cemetary</p>
		</div>
		<div id="g-ai2-2" class="g-text-shadow g-aiAbs g-aiPointText" style="top:30.6497%;margin-top:-15.9px;left:65.564%;width:99px;">
			<p class="g-pstyle0">Netherlands</p>
			<p class="g-pstyle0">Carillon</p>
		</div>
		<div id="g-ai2-3" class="g-text-shadow g-aiAbs g-aiPointText" style="top:46.2494%;margin-top:-15.9px;left:74.505%;width:136px;">
			<p class="g-pstyle0">U.S. Marine Corps</p>
			<p class="g-pstyle0">War Memorial</p>
		</div>
		<div id="g-ai2-4" class="g-text-shadow g-aiAbs g-aiPointText" style="top:55.4792%;margin-top:-8.4px;left:32.8015%;width:31px;">
			<p class="g-pstyle0">C</p>
		</div>
		<div id="g-ai2-5" class="g-text-shadow g-aiAbs g-aiPointText" style="top:57.1363%;margin-top:-13.8px;left:71.4372%;margin-left:-44px;width:88px;">
			<p class="g-pstyle1">Additional</p>
			<p class="g-pstyle1">garden beds</p>
		</div>
		<div id="g-ai2-6" class="g-text-shadow g-aiAbs g-aiPointText" style="top:66.1391%;margin-top:-8.4px;left:27.7244%;width:31px;">
			<p class="g-pstyle0">D</p>
		</div>
		<div id="g-ai2-7" class="g-text-shadow g-aiAbs g-aiPointText" style="top:66.919%;margin-top:-8.4px;left:78.1389%;width:31px;">
			<p class="g-pstyle0">A</p>
		</div>
		<div id="g-ai2-8" class="g-text-shadow g-aiAbs g-aiPointText" style="top:68.219%;margin-top:-8.4px;left:66.5028%;width:31px;">
			<p class="g-pstyle0">B</p>
		</div>
		<div id="g-ai2-9" class="g-text-shadow g-aiAbs g-aiPointText" style="top:77.3189%;margin-top:-8.4px;left:48.1525%;width:87px;">
			<p class="g-pstyle0">Beds 1-49</p>
		</div>
		<div id="g-ai2-10" class="g-text-shadow g-aiAbs g-aiPointText" style="top:80.4388%;margin-top:-8.4px;left:30.1707%;width:30px;">
			<p class="g-pstyle0">E</p>
		</div>
		<div id="g-ai2-11" class="g-other g-aiAbs g-aiPointText" style="top:84.6959%;margin-top:-7.8px;left:95.2355%;margin-left:-36px;width:72px;">
			<p class="g-pstyle2">Arlington</p>
		</div>
		<div id="g-ai2-12" class="g-other g-aiAbs g-aiPointText" style="top:93.4471%;margin-top:-6.4px;left:82.5413%;width:68px;">
			<p class="g-pstyle3">VIRGINIA</p>
		</div>
	</div>
{/if}
	<!-- Artboard: desktop -->
{#if width && (width >= 785)}	<div id="g-netherlands-carillon-locator-desktop" class="g-artboard" style="" data-aspect-ratio="1.555" data-min-width="785">
<div style="padding: 0 0 64.3275% 0;"></div>
		<img id="g-netherlands-carillon-locator-desktop-img" class="g-netherlands-carillon-locator-desktop-img g-aiImg" alt="" src="./images/netherlands-carillon-locator-desktop.jpg"/>
		<div id="g-ai3-1" class="g-text-shadow g-aiAbs g-aiPointText" style="top:20.5714%;margin-top:-18px;left:5.2755%;width:153px;">
			<p class="g-pstyle0">Arlington National</p>
			<p class="g-pstyle0">Cemetary</p>
		</div>
		<div id="g-ai3-2" class="g-text-shadow g-aiAbs g-aiPointText" style="top:30.2626%;margin-top:-18px;left:65.5648%;width:110px;">
			<p class="g-pstyle0">Netherlands</p>
			<p class="g-pstyle0">Carillon</p>
		</div>
		<div id="g-ai3-3" class="g-text-shadow g-aiAbs g-aiPointText" style="top:47.2716%;margin-top:-18px;left:77.2071%;width:153px;">
			<p class="g-pstyle0">U.S. Marine Corps</p>
			<p class="g-pstyle0">War Memorial</p>
		</div>
		<div id="g-ai3-4" class="g-text-shadow g-aiAbs g-aiPointText" style="top:55.2816%;margin-top:-9.5px;left:33.5858%;margin-left:-16px;width:32px;">
			<p class="g-pstyle1">C</p>
		</div>
		<div id="g-ai3-5" class="g-text-shadow g-aiAbs g-aiPointText" style="top:56.9377%;margin-top:-13.9px;left:70.9045%;margin-left:-49.5px;width:99px;">
			<p class="g-pstyle2">Additional</p>
			<p class="g-pstyle2">garden beds</p>
		</div>
		<div id="g-ai3-6" class="g-text-shadow g-aiAbs g-aiPointText" style="top:66.9506%;margin-top:-9.5px;left:78.1544%;margin-left:-16.5px;width:33px;">
			<p class="g-pstyle1">A</p>
		</div>
		<div id="g-ai3-7" class="g-text-shadow g-aiAbs g-aiPointText" style="top:66.9506%;margin-top:-9.5px;left:28.8997%;margin-left:-16px;width:32px;">
			<p class="g-pstyle1">D</p>
		</div>
		<div id="g-ai3-8" class="g-text-shadow g-aiAbs g-aiPointText" style="top:67.544%;margin-top:-9.5px;left:66.6674%;margin-left:-16px;width:32px;">
			<p class="g-pstyle1">B</p>
		</div>
		<div id="g-ai3-9" class="g-text-shadow g-aiAbs g-aiPointText" style="top:77.2351%;margin-top:-8.5px;left:48.1538%;width:96px;">
			<p class="g-pstyle3">Beds 1-49</p>
		</div>
		<div id="g-ai3-10" class="g-text-shadow g-aiAbs g-aiPointText" style="top:80.3996%;margin-top:-9.5px;left:31.2581%;margin-left:-15.5px;width:31px;">
			<p class="g-pstyle1">E</p>
		</div>
		<div id="g-ai3-11" class="g-other g-aiAbs g-aiPointText" style="top:84.528%;margin-top:-12.4px;left:95.2124%;margin-left:-40px;width:80px;">
			<p class="g-pstyle4">Arlington</p>
		</div>
		<div id="g-ai3-12" class="g-art g-aiAbs g-aiPointText" style="top:92.9755%;margin-top:-8.1px;left:82.5418%;width:82px;">
			<p class="g-pstyle5">VIRGINIA</p>
		</div>
	</div>
{/if}
</div>

<style lang="scss">
/* stylelint-disable */
	#g-netherlands-carillon-locator-box ,
	#g-netherlands-carillon-locator-box .g-artboard {
		margin:0 auto;
	}
	#g-netherlands-carillon-locator-box p {
		margin:0;
	}
	#g-netherlands-carillon-locator-box .g-aiAbs {
		position:absolute;
	}
	#g-netherlands-carillon-locator-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
	}
	#g-netherlands-carillon-locator-box .g-aiPointText p { white-space: nowrap; }
	#g-netherlands-carillon-locator-mobile-small {
		position:relative;
		overflow:hidden;
	}
	#g-netherlands-carillon-locator-mobile-small p {
		font-family:roboto,helvetica,arial,sans-serif;
		font-weight:bold;
		line-height:12px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:11px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-netherlands-carillon-locator-mobile-small .g-pstyle0 {
		height:12px;
	}
	#g-netherlands-carillon-locator-mobile-small .g-pstyle1 {
		line-height:10px;
		height:10px;
		font-size:9px;
		text-align:center;
	}
	#g-netherlands-carillon-locator-mobile-small .g-pstyle2 {
		height:12px;
		font-size:9px;
		text-align:center;
	}
	#g-netherlands-carillon-locator-mobile-small .g-pstyle3 {
		font-family:arial,helvetica,sans-serif;
		line-height:10px;
		height:10px;
		letter-spacing:0.083em;
		font-size:8px;
		color:rgb(0,0,0);
	}
	#g-netherlands-carillon-locator-mobile-large {
		position:relative;
		overflow:hidden;
	}
	#g-netherlands-carillon-locator-mobile-large p {
		font-family:roboto,helvetica,arial,sans-serif;
		font-weight:bold;
		line-height:14px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:13px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-netherlands-carillon-locator-mobile-large .g-pstyle0 {
		height:14px;
	}
	#g-netherlands-carillon-locator-mobile-large .g-pstyle1 {
		line-height:12px;
		height:12px;
		font-size:11px;
		text-align:center;
	}
	#g-netherlands-carillon-locator-mobile-large .g-pstyle2 {
		line-height:16px;
		height:16px;
	}
	#g-netherlands-carillon-locator-mobile-large .g-pstyle3 {
		height:14px;
		font-size:11px;
		text-align:center;
	}
	#g-netherlands-carillon-locator-mobile-large .g-pstyle4 {
		font-family:arial,helvetica,sans-serif;
		line-height:11px;
		height:11px;
		letter-spacing:0.083em;
		font-size:9px;
		color:rgb(0,0,0);
	}
	#g-netherlands-carillon-locator-tablet {
		position:relative;
		overflow:hidden;
	}
	#g-netherlands-carillon-locator-tablet p {
		font-family:roboto,helvetica,arial,sans-serif;
		font-weight:bold;
		line-height:15px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-netherlands-carillon-locator-tablet .g-pstyle0 {
		height:15px;
	}
	#g-netherlands-carillon-locator-tablet .g-pstyle1 {
		line-height:13px;
		height:13px;
		font-size:12px;
		text-align:center;
	}
	#g-netherlands-carillon-locator-tablet .g-pstyle2 {
		line-height:14px;
		height:14px;
		font-size:12px;
		text-align:center;
	}
	#g-netherlands-carillon-locator-tablet .g-pstyle3 {
		font-family:arial,helvetica,sans-serif;
		line-height:11px;
		height:11px;
		letter-spacing:0.083em;
		font-size:9px;
		color:rgb(0,0,0);
	}
	#g-netherlands-carillon-locator-desktop {
		position:relative;
		overflow:hidden;
	}
	#g-netherlands-carillon-locator-desktop p {
		font-family:roboto,helvetica,arial,sans-serif;
		font-weight:bold;
		line-height:17px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:16px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-netherlands-carillon-locator-desktop .g-pstyle0 {
		height:17px;
	}
	#g-netherlands-carillon-locator-desktop .g-pstyle1 {
		height:17px;
		text-align:center;
	}
	#g-netherlands-carillon-locator-desktop .g-pstyle2 {
		line-height:13px;
		height:13px;
		font-size:14px;
		text-align:center;
	}
	#g-netherlands-carillon-locator-desktop .g-pstyle3 {
		line-height:15px;
		height:15px;
	}
	#g-netherlands-carillon-locator-desktop .g-pstyle4 {
		line-height:23px;
		height:23px;
		font-size:14px;
		text-align:center;
	}
	#g-netherlands-carillon-locator-desktop .g-pstyle5 {
		font-family:arial,helvetica,sans-serif;
		line-height:14px;
		height:14px;
		letter-spacing:0.083em;
		font-size:12px;
		color:rgb(0,0,0);
	}

	/* Custom CSS */
	.g-text-shadow {
    text-shadow: 0px 0px 1px #000, 0px 0px 2px #000, 0px 0px 3px #000, 0px 0px 4px black;
    -webkit-font-smoothing: antialiased;
    line-height: 19px;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 16px;
    text-align: left;
}

/* stylelint-enable */

</style>
<!-- End ai2html - 2026-04-20 11:40 -->

